Icinga/ansible-playbooks

- icinga2-nrpe-agent/defaults/main.yml
- icinga2-nrpe-agent/tasks/icinga2_nrpe_agent_Gentoo.yml
- icinga2-nrpe-agent/tasks/main.yml
- icinga2-nrpe-agent/templates/nrpe.cfg.j2
- icinga2-nrpe-agent/templates/nrpe_Gentoo.cfg.j2
Modification for gentoo distro. Please also consider move of allowed_hosts to variable from inventory group, because there are a lot of use cases where eth0 is not appropriate and should be redefined.
> Gentoofy icinga2-nrpe-agent role

- icinga2-ansible-no-ui/vars/main.yml
This patch makes sure the correct repository for Debian is added.
> icinga2-no-ui: Install correct Debian repository

- doc/getting-started.md
- icinga2-ansible-no-ui/defaults/main.yml
- icinga2-ansible-no-ui/tasks/icinga2_configure.yml
- icinga2-ansible-web2-ui/README.md
- icinga2-ansible-web2-ui/defaults/main.yml
- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_RedHat_install.yml
This was probably broken by the variable rename in 805c25dce9bc45ddc28d0c0c282b278bbd52d677
> Fix web2 DB mix-up

- icinga2-ansible-classic-ui/defaults/main.yml
- icinga2-ansible-classic-ui/tasks/icinga2_classic_ui_Gentoo_install.yml
- icinga2-ansible-classic-ui/tasks/main.yml
- icinga2-ansible-no-ui/tasks/icinga2_Gentoo_install.yml
- icinga2-ansible-no-ui/tasks/main.yml
Added the installation tasks for installing icinga2 and classic ui on a gentoo based system. Added a few variables to steer how it is installed, with USE-flags, so that the user gets the choice of getting the right webserver files installed for them automatically.
> Added Gentoo installation tasks in no-ui and classic-ui roles

- icinga2-ansible-no-ui/tasks/icinga2_Debian_install.yml
- icinga2-ansible-web2-ui/defaults/main.yml
- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml
- icinga2-ansible-web2-ui/tasks/main.yml
Mainly a copy of the RedHat version which uses APT as Package Manager.
Added a Modified Path for the SQL Schema files.
Different Package for Debian
HTH
Thomas
> Added the Debian os Part for Web2 ui. 

- icinga2-ansible-no-ui/defaults/main.yml
Importing repos keys via HTTP without any checks is insecure
> fetch debmon APT repo key via HTTPS

- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml
Add prerequisite due to this error:
`FAILED! => {"changed": false, "failed": true, "msg": "the python mysqldb module is required"}`
> Add python-mysqldb package

- icinga2-ansible-add-hosts/handlers/main.yml
- icinga2-ansible-add-hosts/tasks/icinga2_add_hosts.yml
No restart is needed when changing host definition. `reload` sends SIGHUP, which is enough for Icinga 2.
> Reload icinga2 for host definition change

- icinga2-ansible-add-hosts/README.md
- icinga2-ansible-add-hosts/templates/object_logic.j2
- Adds a more `ansible`-like `icinga_hosts_attributes` variable (which allows variables to be declared in `yaml`, instead of plain icinga2 config syntax)
- Adds the possibility to template out more complex attributes via `host_templates`:
The `icinga_host_templates` allows you to inject more complex
`host_variables` through a template.
In this example, you would add `templatse/icinga/sensors.j2`, e.g.
```
- hosts: monitoring_servers
roles:
- role: icinga2-ansible-add-hosts
configuration_logic: "object"
icinga_host_templates:
- icinga/sensors.j2
```
```
vars.sensors = {
{% for sensor in hostvars[item].sensors %}
"Sensor {{ sensor.name }}" = {
sensor_name = "{{ sensor.name }}"
cpu_temp_crit = {{ sensor.critical }}
cpu_temp_warn = {{ sensor.warning }}
},
{% endfor %}
}
```
Together with an …
> Object logic extensions

- icinga2-ansible-web2-ui/defaults/main.yml
- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml
- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_RedHat_install.yml
The package already provides a default configuration, we have no reason to force a new one if there is no need from the users's point if view
> Make IDO config optional for web2

- icinga2-ansible-no-ui/defaults/main.yml
- icinga2-ansible-no-ui/tasks/icinga2_RedHat_install.yml
Anyone using their own repos should be able to have the option of not installing a public repo on their servers.  This provides that simple flag.
> Provide option to not use public yum repo

- icinga2-ansible-classic-ui/tasks/icinga2_classic_ui_Debian_install.yml
- icinga2-ansible-classic-ui/tasks/icinga2_classic_ui_Gentoo_install.yml
- icinga2-ansible-classic-ui/tasks/icinga2_classic_ui_RedHat_install.yml
- icinga2-ansible-web-ui/tasks/icinga2_web_ui_RedHat_install.yml
- icinga2-ansible-web-ui/tasks/icinga2_web_ui_mysql_RedHat_install.yml
Not properly wrapping with_item with `"{ }"` results in an error as seen here:  https://github.com/ansible/ansible/issues/23496
There is still one here that I wasn't able since jinja2 doesn't support nested variables: https://github.com/pallets/jinja/issues/623  :
```
icinga2-ansible-web-ui/tasks/icinga2_web_ui_mysql_RedHat_install.yml
17:  with_items: icinga2_web_ui_{{ icinga2_web_ui_ido }}_rpm
```
Cheers
> Fixing with_item variable wrapping to support ansible 2.2+'s requirement

- doc/adding-hosts.md
Some links in the adding-hosts.md didn't point to any meaningful location any more, yielding the about page.
This pull request fixes this behaviour.
> Fixed links, pointing to correct locations again

- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml
Ubuntu 18.04 comes with PHP 7.2 instead of 7.0.
> Add support for Ubuntu 18.04

- icinga2-ansible-no-ui/tasks/icinga2_Debian_install.yml
Debmon has been shut down and is not required any more.
> Remove Debmon key and repository

- icinga2-ansible-no-ui/defaults/main.yml
- icinga2-ansible-no-ui/tasks/icinga2_Debian_install.yml
- icinga2-ansible-no-ui/tasks/icinga2_Ubuntu_install.yml
packages.icinga.org has an invalid TLS certificate, so apt-get update
fails loudly. This changes the repo URL to packages.icinga.com (which
has a valid certificate, and to which packages.icinga.org also
redirects).
This fixes #88.
> change Apt repos (#88)

- icinga2-ansible-no-ui/defaults/main.yml
apt-key gave error as the site's canonical hostname is now packages.icinga.com (and the certificate is for this URL). Changed URL in the config to fix.
> Fixing URL for icinga.com (not .org)

- doc/installation.md
There seems to have been no formatting done at all for using MarkDown in any way....
Plus, manually putting in a `$` does not signify a code block, not to mention it gets in the way.
> Fix the Markdown Formatting

- icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml
In issue https://github.com/Icinga/ansible-playbooks/issues/72 , there are two similar comments mentioning icingaweb requires additional privileges.   
> Same problem here.GRANT ALL ON icingaweb.* TO icingaweb@localhost or modifying the privileges in icinga2_web2_ui_Debian_install.yml solves the problem.
And I also encountered this today.
> fix icinga2_web2_db privileges

- icinga2-ansible-no-ui/tasks/icinga2_Debian_MySQL_install.yml
Needed for Icinga 2.11.
see https://icinga.com/docs/icinga2/latest/doc/02-installation/#debian-backports-repository
> Add backport repository for Debian Stretch

- icinga2-ansible-add-hosts/templates/object_logic.j2
- icinga2-ansible-no-ui/templates/icinga2_check_commands.j2
because it is supported by python2 and python3
With this change it should be possible to use python2 or python3 for this playbooks. Python3 does not have 'iteritems()' anymore
> Changes 'iteritems()' to 'items() | list' (python3 support)
